### ISSUE TITLE
Parsing bug

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/entity-api#204]
Error:
````
[2021-07-16 02:03:40] DEBUG in schema_manager: Invalid expression (string value) of key: image_files for ast.literal_eval()
[2021-07-16 02:03:40] DEBUG in schema_manager: [{'filename': '20181208_161237.jpg', 'file_uuid': '176dc2ea6d3ae371d1ae74a921bda8da', 'description': 'deceased donor right kidney with ureter'}
[2021-07-16 02:03:40] ERROR in schema_manager: Failed to convert the source string with ast.literal_eval()
Traceback (most recent call last):
  File "./schema/schema_manager.py", line 552, in normalize_entity_result_for_response
    entity_dict[key] = ast.literal_eval(entity_dict[key])
  File "/usr/lib64/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    [{'filename': '20181208_161237.jpg', 'file_uuid': '176dc2ea6d3ae371d1ae74a921bda8da', 'description': 'deceased donor right kidney with ureter'}
                                                                                                                                                  ^
SyntaxError: unexpected EOF while parsing

````

The entity causing this issue: https://entity.api.hubmapconsortium.org/entities/b34c049c809533ca3ab0220670cb1632

````
{
    "created_by_user_displayname": "Diane Salamon",
    "created_by_user_email": "salamond@wustl.edu",
    "created_by_user_sub": "a00bec30-ca4d-4df5-9d96-14d0ccd601a1",
    "created_timestamp": 1577728543930,
    "data_access_level": "public",
    "direct_ancestor": {
        "created_by_user_displayname": "Diane Salamon",
        "created_by_user_email": "salamond@wustl.edu",
        "created_by_user_sub": "a00bec30-ca4d-4df5-9d96-14d0ccd601a1",
        "created_timestamp": 1577728454154,
        "data_access_level": "public",
        "entity_type": "Donor",
        "group_name": "University of California San Diego TMC",
        "group_uuid": "03b3d854-ed44-11e8-8bce-0e368f3075e8",
        "hubmap_id": "HBM289.BLHF.363",
        "lab_donor_id": "KTRC_PPID_3499",
        "label": "3499",
        "last_modified_timestamp": 1578499032090,
        "metadata": {
            "organ_donor_data": [
                {
                    "code": "1086007",
                    "concept_id": "C0086287",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "57312000",
                    "grouping_concept": "C1522384",
                    "grouping_concept_preferred_term": "Sex",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Female",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "413773004",
                    "concept_id": "C0007457",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "415229000",
                    "grouping_concept": "C0034510",
                    "grouping_concept_preferred_term": "Race",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "White",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "424144002",
                    "concept_id": "C0001779",
                    "data_type": "Numeric",
                    "data_value": "57",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "424144002",
                    "grouping_concept": "C0001779",
                    "grouping_concept_preferred_term": "Age",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "EQ",
                    "preferred_term": "Age",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": "years"
                },
                {
                    "code": "60621009",
                    "concept_id": "C1305855",
                    "data_type": "Numeric",
                    "data_value": "19.6",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "60621009",
                    "grouping_concept": "C1305855",
                    "grouping_concept_preferred_term": "Body mass index",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "EQ",
                    "preferred_term": "Body mass index",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": "kg/m^2"
                },
                {
                    "code": "27113001",
                    "concept_id": "C0005910",
                    "data_type": "Numeric",
                    "data_value": "50.2",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "27113001",
                    "grouping_concept": "C0005910",
                    "grouping_concept_preferred_term": "Weight",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "EQ",
                    "preferred_term": "Weight",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": "kg"
                },
                {
                    "code": "50373000",
                    "concept_id": "C0005890",
                    "data_type": "Numeric",
                    "data_value": "160",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "50373000",
                    "grouping_concept": "C0005890",
                    "grouping_concept_preferred_term": "Height",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "EQ",
                    "preferred_term": "Height",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": "cm"
                },
                {
                    "code": "112144000",
                    "concept_id": "C0427620",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "44608003",
                    "grouping_concept": "C0005844",
                    "grouping_concept_preferred_term": "Blood type",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "A",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "410429000",
                    "concept_id": "C0018790",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "392521001",
                    "grouping_concept": "C0262926",
                    "grouping_concept_preferred_term": "Medical history",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Cardiac arrest",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "230690007",
                    "concept_id": "C0038454",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "184305005",
                    "grouping_concept": "C0007465",
                    "grouping_concept_preferred_term": "Cause of death",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Cerebrovascular accident",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "73211009",
                    "concept_id": "C0011849",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "392521001",
                    "grouping_concept": "C0262926",
                    "grouping_concept_preferred_term": "Medical history",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Diabetes",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "38341003",
                    "concept_id": "C0020538",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "392521001",
                    "grouping_concept": "C0262926",
                    "grouping_concept_preferred_term": "Medical history",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Hypertension",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "53741008",
                    "concept_id": "C1956346",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "392521001",
                    "grouping_concept": "C0262926",
                    "grouping_concept_preferred_term": "Medical history",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Coronary artery disease",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "77176002",
                    "concept_id": "C0337664",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "160476009",
                    "grouping_concept": "C0424945",
                    "grouping_concept_preferred_term": "Social history",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Smoker",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "1386000",
                    "concept_id": "C0151699",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "246078001",
                    "grouping_concept": "C0449413",
                    "grouping_concept_preferred_term": "Mechanism of injury",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Intracranial hemorrhage",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "38605008",
                    "concept_id": "C0277610",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "419620001",
                    "grouping_concept": "C0011065",
                    "grouping_concept_preferred_term": "Death event",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Natural causes",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                }
            ]
        },
        "protocol_url": "dx.doi.org/10.17504/protocols.io.568g9hw",
        "submission_id": "UCSD0006",
        "uuid": "f8d963cab6bd10e2a4b8184ea8197fc1"
    },
    "entity_type": "Sample",
    "group_name": "University of California San Diego TMC",
    "group_uuid": "03b3d854-ed44-11e8-8bce-0e368f3075e8",
    "hubmap_id": "HBM482.CMSP.343",
    "image_file_metadata": [
        {
            "description": "deceased donor right kidney with ureter",
            "filepath": "/hive/hubmap/lz/tissue-reg-data/03b3d854-ed44-11e8-8bce-0e368f3075e8/b34c049c809533ca3ab0220670cb1632/20181208_161237.jpg"
        },
        {
            "description": "bivalved ",
            "filepath": "/hive/hubmap/lz/tissue-reg-data/03b3d854-ed44-11e8-8bce-0e368f3075e8/b34c049c809533ca3ab0220670cb1632/20181208_162620.jpg"
        }
    ],
    "image_files": "[{'filename': '20181208_161237.jpg', 'file_uuid': '176dc2ea6d3ae371d1ae74a921bda8da', 'description': 'deceased donor right kidney with ureter'}",
    "lab_tissue_sample_id": "3499",
    "last_modified_timestamp": 1617750835897,
    "last_modified_user_displayname": "HuBMAP Process",
    "last_modified_user_email": "hubmap@hubmapconsortium.org",
    "last_modified_user_sub": "3e7bce63-129d-33d0-8f6c-834b34cd382e",
    "organ": "RK",
    "protocol_url": "dx.doi.org/10.17504/protocols.io.568g9hw",
    "specimen_type": "organ",
    "submission_id": "UCSD0006-RK",
    "uuid": "b34c049c809533ca3ab0220670cb1632"
}
````

@shirey is this the Sample entity created by someone using the entity-api directly instead of the UI? I'm wondering why the closing ] is missing. That's causing the parsing error so it returned as a string rather than json:

````
"image_files": "[{'filename': '20181208_161237.jpg', 'file_uuid': '176dc2ea6d3ae371d1ae74a921bda8da', 'description': 'deceased donor right kidney with ureter'}",
````

**Comment by yuanzhou** [comment]
The entity causing this issue: https://entity.api.hubmapconsortium.org/entities/b34c049c809533ca3ab0220670cb1632

````
{
    "created_by_user_displayname": "Diane Salamon",
    "created_by_user_email": "salamond@wustl.edu",
    "created_by_user_sub": "a00bec30-ca4d-4df5-9d96-14d0ccd601a1",
    "created_timestamp": 1577728543930,
    "data_access_level": "public",
    "direct_ancestor": {
        "created_by_user_displayname": "Diane Salamon",
        "created_by_user_email": "salamond@wustl.edu",
        "created_by_user_sub": "a00bec30-ca4d-4df5-9d96-14d0ccd601a1",
        "created_timestamp": 1577728454154,
        "data_access_level": "public",
        "entity_type": "Donor",
        "group_name": "University of California San Diego TMC",
        "group_uuid": "03b3d854-ed44-11e8-8bce-0e368f3075e8",
        "hubmap_id": "HBM289.BLHF.363",
        "lab_donor_id": "KTRC_PPID_3499",
        "label": "3499",
        "last_modified_timestamp": 1578499032090,
        "metadata": {
            "organ_donor_data": [
                {
                    "code": "1086007",
                    "concept_id": "C0086287",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "57312000",
                    "grouping_concept": "C1522384",
                    "grouping_concept_preferred_term": "Sex",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Female",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "413773004",
                    "concept_id": "C0007457",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "415229000",
                    "grouping_concept": "C0034510",
                    "grouping_concept_preferred_term": "Race",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "White",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "424144002",
                    "concept_id": "C0001779",
                    "data_type": "Numeric",
                    "data_value": "57",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "424144002",
                    "grouping_concept": "C0001779",
                    "grouping_concept_preferred_term": "Age",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "EQ",
                    "preferred_term": "Age",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": "years"
                },
                {
                    "code": "60621009",
                    "concept_id": "C1305855",
                    "data_type": "Numeric",
                    "data_value": "19.6",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "60621009",
                    "grouping_concept": "C1305855",
                    "grouping_concept_preferred_term": "Body mass index",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "EQ",
                    "preferred_term": "Body mass index",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": "kg/m^2"
                },
                {
                    "code": "27113001",
                    "concept_id": "C0005910",
                    "data_type": "Numeric",
                    "data_value": "50.2",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "27113001",
                    "grouping_concept": "C0005910",
                    "grouping_concept_preferred_term": "Weight",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "EQ",
                    "preferred_term": "Weight",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": "kg"
                },
                {
                    "code": "50373000",
                    "concept_id": "C0005890",
                    "data_type": "Numeric",
                    "data_value": "160",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "50373000",
                    "grouping_concept": "C0005890",
                    "grouping_concept_preferred_term": "Height",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "EQ",
                    "preferred_term": "Height",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": "cm"
                },
                {
                    "code": "112144000",
                    "concept_id": "C0427620",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "44608003",
                    "grouping_concept": "C0005844",
                    "grouping_concept_preferred_term": "Blood type",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "A",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "410429000",
                    "concept_id": "C0018790",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "392521001",
                    "grouping_concept": "C0262926",
                    "grouping_concept_preferred_term": "Medical history",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Cardiac arrest",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "230690007",
                    "concept_id": "C0038454",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "184305005",
                    "grouping_concept": "C0007465",
                    "grouping_concept_preferred_term": "Cause of death",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Cerebrovascular accident",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "73211009",
                    "concept_id": "C0011849",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "392521001",
                    "grouping_concept": "C0262926",
                    "grouping_concept_preferred_term": "Medical history",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Diabetes",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "38341003",
                    "concept_id": "C0020538",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "392521001",
                    "grouping_concept": "C0262926",
                    "grouping_concept_preferred_term": "Medical history",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Hypertension",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "53741008",
                    "concept_id": "C1956346",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "392521001",
                    "grouping_concept": "C0262926",
                    "grouping_concept_preferred_term": "Medical history",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Coronary artery disease",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "77176002",
                    "concept_id": "C0337664",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "160476009",
                    "grouping_concept": "C0424945",
                    "grouping_concept_preferred_term": "Social history",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Smoker",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "1386000",
                    "concept_id": "C0151699",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "246078001",
                    "grouping_concept": "C0449413",
                    "grouping_concept_preferred_term": "Mechanism of injury",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Intracranial hemorrhage",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                },
                {
                    "code": "38605008",
                    "concept_id": "C0277610",
                    "data_type": "Nominal",
                    "data_value": "",
                    "end_datetime": "",
                    "graph_version": "UMLS2019AA",
                    "grouping_code": "419620001",
                    "grouping_concept": "C0011065",
                    "grouping_concept_preferred_term": "Death event",
                    "grouping_sab": "SNOMEDCT_US",
                    "numeric_operator": "",
                    "preferred_term": "Natural causes",
                    "sab": "SNOMEDCT_US",
                    "start_datetime": "0",
                    "units": ""
                }
            ]
        },
        "protocol_url": "dx.doi.org/10.17504/protocols.io.568g9hw",
        "submission_id": "UCSD0006",
        "uuid": "f8d963cab6bd10e2a4b8184ea8197fc1"
    },
    "entity_type": "Sample",
    "group_name": "University of California San Diego TMC",
    "group_uuid": "03b3d854-ed44-11e8-8bce-0e368f3075e8",
    "hubmap_id": "HBM482.CMSP.343",
    "image_file_metadata": [
        {
            "description": "deceased donor right kidney with ureter",
            "filepath": "/hive/hubmap/lz/tissue-reg-data/03b3d854-ed44-11e8-8bce-0e368f3075e8/b34c049c809533ca3ab0220670cb1632/20181208_161237.jpg"
        },
        {
            "description": "bivalved ",
            "filepath": "/hive/hubmap/lz/tissue-reg-data/03b3d854-ed44-11e8-8bce-0e368f3075e8/b34c049c809533ca3ab0220670cb1632/20181208_162620.jpg"
        }
    ],
    "image_files": "[{'filename': '20181208_161237.jpg', 'file_uuid': '176dc2ea6d3ae371d1ae74a921bda8da', 'description': 'deceased donor right kidney with ureter'}",
    "lab_tissue_sample_id": "3499",
    "last_modified_timestamp": 1617750835897,
    "last_modified_user_displayname": "HuBMAP Process",
    "last_modified_user_email": "hubmap@hubmapconsortium.org",
    "last_modified_user_sub": "3e7bce63-129d-33d0-8f6c-834b34cd382e",
    "organ": "RK",
    "protocol_url": "dx.doi.org/10.17504/protocols.io.568g9hw",
    "specimen_type": "organ",
    "submission_id": "UCSD0006-RK",
    "uuid": "b34c049c809533ca3ab0220670cb1632"
}
````

@shirey is this the Sample entity created by someone using the entity-api directly instead of the UI? I'm wondering why the closing ] is missing. That's causing the parsing error so it returned as a string rather than json:

````
"image_files": "[{'filename': '20181208_161237.jpg', 'file_uuid': '176dc2ea6d3ae371d1ae74a921bda8da', 'description': 'deceased donor right kidney with ureter'}",
````

**Comment by shirey** [comment]
@yuanzhou This likely happened when I manually modified download files at some point.  Let me know if you want me to fix it.

**Comment by yuanzhou** [comment]
@shirey sounds like a data issue. Yes, if you get a chance to double check that'll be great and I'll test, thanks.

**Comment by shirey** [comment]
@yuanzhou This should be fixed now.

**Comment by yuanzhou** [comment]
@shirey yup, I tested against PROD and looking good now. Can you also fix it on DEV/TEST/STAGE neo4j if it's not too much hassle.

**Comment by yuanzhou** [comment]
Same issue happened again: https://github.com/hubmapconsortium/manual-data-ingest/issues/46
